# THYMELEAF (ThymeleafAutoConfiguration) 
spring:
  thymeleaf:
    cache: true
    check-template: true
    check-template-location: true
    enabled: true
    encoding: UTF-8
    mode: HTML
    prefix: classpath:/templates/
    suffix: .html
  datasource:
    url: jdbc:mysql//localhost:3306/mydb
    username: root
    password: 'Acceso2018#'
    platform: mysql
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    show-sql: true
#    database-platform: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      ddl-auto: update
#      naming:
#        implicit-strategy: org.hibernate.cfg.ImprovedNamingStrategy
#        physical-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
  data:
    jpa:
      repositories:
        enabled: true        
